feat: Made View Individual Role Listings Dynamic and Added Viewing of Matched and Unmatched skills
IS212-G9-T5/skill-based-role-portal pull request #13
Opened 2023-09-30 08:25 UTC by christianmk04

### 📋 Overview (what is this PR about) 

Made View Individual Role Listings Dynamic, so now when a staff member clicks on a role listing from the view available role listings page, the details of the role with the corresponding ID should show.

For each of the role listings, the user should be able to see all the skills that they have, as well as the skills they have that are matched and all the skills they don't have (unmatched skills). They should be able to see the number and the percentage of matched skills for the role listing.

For the skills that they have, user can click on a skill chip to view the description of the skill as a modal popup.

### 🚀 What are the features/changes included?
URL to call the specific role listing from the backend is no longer hardcoded by dynamically taken from the id in the url of the page.

### 🧪 What testing have I done to make sure it is working?
Have manually went to click on several role listings on the View Available Role Listings page to see if the correct details are shown.

### 🧐 How should the reviewer go about testing it?
Reviewer can click on any role listings on the View Available Role Listings page and take a look if the correct details are shown

### ✅ Final check
- [ ] I have done the following:
  - `<git rebase main>` to replay your feature commits from the main branch
  - If there are any conflicts, resolve them then run:
    - `git add <resolved rebase conflict files>`
    - `<git rebase --continue>`
    - You may need to run `<git pull>` if your local feature branch is behind the remote feature branch
    - `<git push>`

### 🖼️ Make it visual ✨ (if possible, attach a screenshot of what the reviewer is supposed to see)

<img width="1238" alt="image" src="https://github.com/IS212-G9-T5/skill-based-role-portal/assets/111347751/0f92b545-ed18-4a32-9041-4eee52ac3e2a">
Role Listing for Role with ID 20
 
<img width="1239" alt="image" src="https://github.com/IS212-G9-T5/skill-based-role-portal/assets/111347751/ad8f4f17-90b0-4dc0-8c17-2fb94c8acec5">
Role Listing for Role with ID 156

### ✍️ Any additional notes
NIL

2023-09-30 10:49 UTC, Jaylin0312 requested changes

2023-09-30 10:49 UTC, Jaylin0312 commented on frontend/src/pages/applicant/main.tsx
Consider using `fetch("/api/...")` (either relative path or URL) instead of `axios` since we are not making any complex requests, and also to make the frontend code consistent (the rest of the components are using `Fetch`).

More about how to use `Fetch`: https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch
More about difference between `Fetch` and `Axios`: https://www.geeksforgeeks.org/difference-between-fetch-and-axios-js-for-making-http-requests/

2023-10-02 09:39 UTC, christianmk04 commented on frontend/src/pages/applicant/main.tsx
It is already using fetch to call

2023-10-10 11:59 UTC, Jaylin0312 requested changes

2023-10-10 11:59 UTC, Jaylin0312 commented on frontend/src/index.css
Will suggest to use tailwindcss instead of having another css file since we are using tailwindcss alr :DD

2023-10-10 11:59 UTC, Jaylin0312 commented on frontend/src/pages/applicant/AllRoleListing.tsx
> +// import axios from "axios"
Can just remove this instead of commenting

2023-10-10 11:59 UTC, Jaylin0312 commented on frontend/src/types.d.ts
Is this a new file? There should already be a global type file under `src/types/global.d.ts`

2023-10-10 17:28 UTC, christianmk04 commented on frontend/src/types.d.ts
i think when i merged the last time from someone's branch, this file was missing so i created a new one but then when i rebased or merged this file came back, but yeah i think its the same

2023-10-10 17:31 UTC, christianmk04 commented on frontend/src/types.d.ts
will remove this types.d.ts

2023-10-11 04:06 UTC, Jaylin0312 requested changes

2023-10-11 04:06 UTC, Jaylin0312 commented on frontend/src/pages/applicant/main.tsx
> +  }, []);
Can help to refactor by extracting this logic to api folder (same as other api calls)

2023-10-11 07:16 UTC, Jaylin0312 commented on frontend/src/pages/applicant/main.tsx
> +  }, []);
Updated in latest commit

2023-10-11 07:17 UTC, Jaylin0312 commented
Overall looks good to me, thanks for the nice work! Merging this into main

2023-10-11 07:18 UTC, merged